### ISSUE TITLE
Firebase connectivity

### ISSUE THREAD

**Issue by DJ73** [ICE18/ICE#1]
The login screen (combined v2) is ready and has two functions - new and connect.
**New** should make a new entry for the user and project and then call connect.
**Connect** should connect and start the editor (to be done later)

Add a _question_ issue if you have any queries.

**Comment by Kashish-Sharma** [comment]
Added create button onClick, now creating new Project and User on clicking create button.
Name and Id same for both project and user, need to create a standard function for generating unique Ids
