### ISSUE TITLE
Line transform

### ISSUE THREAD

**Issue by DJ73** [ICE18/ICE#11]
Fabric.js provides 8 control points for tranformation of line out of which 6 have been disabled. This makes selecting the other 2 points very difficult.
**Preferred**: Just have 2 control points at the ends

**Comment by Kashish-Sharma** [comment]
Fix: Added a toggle mechanism onClick line button (Similar to paint)
      This makes rest of the canvas unselectable along with each object on it.
      OnClicking line button again toggles back the changes.
